export const mobileExtraMenu = [
  {
    id: 777,
    label: 'Worksmart',
    route: 'worksmart',
    children: [],
  },
  {
    id: 888,
    label: 'Ebco',
    route: 'ebco',
    children: [],
  },
  {
    id: 999,
    label: 'Livsmart',
    route: 'livsmart',
    children: [],
  },
  {
    id: 1001,
    label: 'About Us',
    route: 'company',
    isOpen: false,
    children: [
      {
        id: 1002,
        label: 'Company',
        route: 'company',
        isOpen: false,
        children: [],
      },
      {
        id: 1003,
        label: 'Sustainability at EBCO',
        route: 'sustainability-at-ebco',
        isOpen: false,
        children: [],
      },
      {
        id: 1004,
        label: 'Initiatives',
        route: 'initiatives',
        isOpen: false,
        children: [],
      },
      {
        id: 1005,
        label: 'Certification',
        route: 'certification',
        isOpen: false,
        children: [],
      },
      {
        id: 1006,
        label: 'Investor Relations',
        route: 'investor-relations',
        isOpen: false,
        children: [],
      },
    ],
  },
  {
    id: 1107,
    label: 'Shop Now',
    route: 'shop-now',
    children: [],
  },
  {
    id: 1007,
    label: 'Discovery Centers',
    route: 'discovery-centers',
    isOpen: false,
    children: [],
  },
  {
    id: 1009,
    label: 'Distribution Network',
    route: 'distribution-network',
    isOpen: false,
    children: [],
  },
  {
    id: 1008,
    label: 'News And Events',
    route: 'news-and-events',
    isOpen: false,
    children: [],
  },

  {
    id: 1010,
    label: 'Downloads',
    route: 'downloads',
    isOpen: false,
    children: [],
  },
  {
    id: 1016,
    label: 'Blogs & Articles',
    route: 'blogs-articles',
    children: [],
  },
  {
      id: 1015,
      label: "Designer's Inspirations",
      route: "designer-inspiration",
      children: [],
  },
  {
    id: 1011,
    label: 'Videos',
    route: 'videos?tab=0',
    isOpen: false,
    children: [],
  },

  {
    id: 1012,
    label: 'Contact Us',
    route: 'contact-us',
    isOpen: false,
    children: [],
  },
  {
    id: 1013,
    label: 'Distributor Login',
    route: '',
    isOpen: false,
    children: [],
  },
]
